device: 'cuda:0'
model: 'vgg19_bn'
is_couple: False

amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
log_file_name:
dataset_path: './data'
dataset: 'tiny'

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-4
frequency_save: 0

random_seed: 0
seed: 0

ratio: 0.01
index: 

layerwise_ratio: [0.01, 0.01, 0.03, 0.09, 0.27, 0.10]